### PR TITLE
add Salvator-XS with H3 ES2.0 machine

### PR DESCRIPTION
**Pull request by iartemenko**

### CODE REVIEW

**Comment by otyshchenko1** [comment]
Where actually r8a7795-salvator-xs-doma.dts?

**Comment by iartemenko** [comment]
Updated and tested on target board.

**Comment by andr2000** [comment]
were comments raised by @otyshchenko1 addressed?

**Comment by iartemenko** [comment]
r8a7795-salvator-xs-doma.dts is present in the file tree since commit  d4d305e5b6f0d1138addf0af50e6eb24dca02ada Date:   Thu Jun 7 16:37:21 2018, so this pull request only adds it into the recipe file.
Suggested by @otyshchenko1 patch was cherry-picked as well, please have a look at  https://github.com/xen-troops/meta-xt-prod-devel/pull/95/commits/56a323117390f69b28877f985353a9d0b43b2f4d

**Pull request merged**
