### PR TITLE
Remove support for salvator-xs-h3-2x2g

### PR DESCRIPTION
**Pull request by otyshchenko1**
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>

### CODE REVIEW

**Comment by iusyk** [comment]
maybe I am wrong , but i think the following config files have to be deleted as well
xt-distro/meta/conf/machine/salvator-xs-h3-2x2g.conf
meta-xt-images/machine/meta-xt-images-rcar-gen3/conf/machine/salvator-xs-h3-2x2g-xt.conf

or .. ?

**Comment by otyshchenko1** [comment]
> maybe I am wrong , but i think the following config files have to be deleted as well
> xt-distro/meta/conf/machine/salvator-xs-h3-2x2g.conf
> meta-xt-images/machine/meta-xt-images-rcar-gen3/conf/machine/salvator-xs-h3-2x2g-xt.conf
> 
> or .. ?

Yes, you are completely right. I will remove these as well.

**Comment by otyshchenko1** [comment]
Done. Please see:
https://github.com/xen-troops/meta-xt-images/pull/147
https://github.com/xen-troops/xt-distro/pull/44

**Comment by rshym** [comment]
Taking into account that we remove files in meta-xt-distro and xt-distro, we need to check that same change is required for other supported products: tu and aos.

**Comment by otyshchenko1** [comment]
> Taking into account that we remove files in meta-xt-distro and xt-distro, we need to check that same change is required for other supported products: tu and aos.

Sounds reasonable, @iusyk could you take a look at?

**Pull request merged**
