### PR TITLE
move the common code from rcar-proprietary-graphic.bb into inc rcar-p…

### PR DESCRIPTION
**Pull request by iusyk**
move common code from rcar-proprietary-graphic.bb to new file proprietary-graphic.inc

path to rcar-proprietary-graphic.inc is meta-xt-images-vgpu/recipes-graphics/gles-module
Motivation :
The recipe has almost the same body for both domd and domu branch, for the case if changes are required (like https://github.com/xen-troops/meta-xt-prod-gen3-test/issues/164),
it is necessary to do the same changes in both recipes. To avoid a double work and mitigate the risk of the errors, it has been decided to move the common implementaion in separate .inc file
Now, recipe has just a value to be defined SRC_URI.

### CODE REVIEW

**Comment by andr2000** [comment]
Is "recipes-graphics/gles-module/rcar-proprietary-graphic.inc" missing in this PR?

**Comment by otyshchenko1** [comment]
@iusyk, would you please format your commit messages according to the standard rules? Also could you please remove the link to other product's issue form patch description.

**Comment by otyshchenko1** [comment]
Including a file from other meta-layer doesn't seem to be good idea, but I am afraid I don't suggest a better solution. Could you please mark this patch as a hack/temp and add corresponding TODO to the patch description.

**Comment by iusyk** [comment]
> Is "recipes-graphics/gles-module/rcar-proprietary-graphic.inc" missing in this PR?

unfortunately, this file belongs to meta-xt-layer, see PR https://github.com/xen-troops/meta-xt-images/pull/154

**Comment by iusyk** [comment]
> Including a file from other meta-layer doesn't seem to be good idea, but I am afraid I can't suggest a better solution. Could you please mark this patch as a hack/temp and add corresponding TODO to the patch description.

done

**Comment by iusyk** [comment]
> @iusyk, could you please format your commit messages according to the standard rules? Also could you please remove the link to other product's issue form patch description.

done

**Comment by otyshchenko1** [comment]
I suggest to keep changes to rcar-proprietary-graphic.bb as a separate patch and not to mix with removing unneeded headers.

**Comment by iusyk** [comment]
> I suggest to keep changes to rcar-proprietary-graphic.bb as a separate patch and not to mix with removing unneeded headers.

done

**Comment by otyshchenko1** [comment]
lgtm, (just nitpicking: could you please leave either "hack" or "temp" as a prefix, but not both)

**Pull request merged**
