### PR TITLE
doma: Extend supported audio sample rates

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by andr2000** [comment]
I believe this now changes the sampling rates for all supported machines. If this is the case then:
`Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>`

**Comment by rshym** [comment]
Correct, this is intended to work on all supported machines.

**Comment by rshym** [comment]
'Reviewed-by' added to message.

**Comment by rshym** [comment]
@iartemenko Could you please merge? Patch reviewed.

**Pull request merged**
