### PR TITLE
dev86-native: Use github link for SRC_URI

### PR DESCRIPTION
**Pull request by iartemenko**
Temporary solution until error below is fixed.

This site can’t be reached
v3.sk took too long to respond.
Search Google for sk ~lkundrak dev86 archive Dev86src tar
ERR_CONNECTION_TIMED_OUT

Signed-off-by: Iurii Artemenko <iurii_artemenko@epam.com>

### CODE REVIEW

**Comment by lorc** [comment]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by otyshchenko1** [comment]
What about dom0 recipe?

**Comment by iartemenko** [comment]
Updated

**Comment by otyshchenko1** [comment]
Tested for devel-src with DomU

**Pull request merged**
