### PR TITLE
Wait for device to be accessible

### PR DESCRIPTION
**Pull request by rshym**
Add waiting for block device, to be sure that it is accessible
by losetup.

Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

### CODE REVIEW

**Comment by rshym** [comment]
Comment addressed: Suggested-by added.

**Comment by aanisov** [comment]
@arminn do you have any concerns?

**Comment by arminn** [comment]
No concerns, from my experience - this change is useful.

**Comment by aanisov** [comment]
@arminn and RB?

**Comment by arminn** [comment]
Reviewed-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>

**Pull request merged**
