### PR TITLE
prod-devel: upgrade XEN

### PR DESCRIPTION
**Pull request by aanisov**
Promote used XEN version to 4.10.0.

Signed-off-by: Andrii Anisov <andrii_anisov@epam.com>

### CODE REVIEW

**Comment by otyshchenko1** [comment]
@iartemenko please take care of this stuff to reach gen3-test1. As we are going to use XEN 4.10 too.

**Comment by otyshchenko1** [comment]
Yo, is anyone else going to review?

**Comment by lorc** [comment]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by aanisov** [comment]
@iartemenko be so kind to merge this together with https://github.com/xen-troops/meta-xt-images/pull/82 and switching xen/master to 4.10-rebase. Do not forget to tag current xen/master/HEAD with final tag as described in  https://docs.google.com/document/d/1-L24L1oqc3oOEQctXGQAiaik8bbQRDDPXc0lCjzMiNc/edit

**Pull request merged**
