### PR TITLE
MC-enabled PV camera backend and "HDMI_IN camera" integration

### PR DESCRIPTION
**Pull request by otyshchenko1**
Please note that the following patches are not for review, just for possibility to build and test: 
- [DO NOT MERGE] Enable PV Camera support
- [DO NOT MERGE] Switch to local repo until camera_be is not merged

Corresponding PR https://github.com/xen-troops/camera_be/pull/9

### CODE REVIEW

**Comment by otyshchenko1** [comment]
TODO: need to investigate for what machines (among all supported) "HDMI_IN camera" should be set

**Comment by otyshchenko1** [comment]
Tested HDMI_IN & CVBS with DomU

**Comment by andr2000** [comment]
`Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>`

**Comment by otyshchenko1** [comment]
Update by adding R-b and removing "NOT FOR MERGE" patches

**Comment by otyshchenko1** [comment]
I forgot to mention that PR request with R-Car VIN connected cameras was tested on salvator-x-h3-4x2g machine only.

**Pull request merged**
