### PR TITLE
Wwwivi support

### PR DESCRIPTION
**Pull request by iusyk**

### CODE REVIEW

**Comment by andr2000** [comment]
Why do you need to do this at run-time? I think this can easily be done while installing hosts file?

**Comment by iusyk** [comment]
inside of rootfs tar
etc/systemd/network/xenbr0.network:Address=192.168.0.1/24
etc/dnsmasq.conf:#server=/localnet/192.168.0.1
etc/dnsmasq.conf:#dhcp-range=192.168.0.50,192.168.0.150,12h
etc/dnsmasq.conf:#dhcp-range=192.168.0.50,192.168.0.150,255.255.255.0,12h
etc/dnsmasq.conf:#dhcp-range=red,192.168.0.50,192.168.0.150
etc/dnsmasq.conf:dhcp-range=192.168.0.2,192.168.0.150,12h
var/lib/opkg/info/netbase.postinst:    if ! grep -q '192.168.0.1   wwwivi' $D/etc/hosts ; then
var/lib/opkg/info/netbase.postinst:        echo '192.168.0.1   wwwivi' >> $D/etc/hosts

**Comment by otyshchenko1** [comment]
I am not sure this is really needed for build with DomU. Maybe change should be applied for DomA based build only?

**Comment by andr2000** [comment]
```
recipes-core/netbase$ cat netbase_%.bbappend 
do_install_append () {
	# for VIS
	echo "192.168.0.1 wwwivi" >> ${D}${sysconfdir}/hosts
}

```

**Comment by iusyk** [comment]
> I am not sure this is really needed for build with DomU. Maybe change should be applied for DomA based build only?

do you mean to add mentioned code just for doma ?
i think it is reasonable

**Comment by iusyk** [comment]
> Why do you need to do this at run-time? I think this can easily be done while installing hosts file?

really, the implemented approach was based at already approved and merged one, it was just a reason to implement it

**Comment by rshym** [comment]
Fully agree with andr200 proposal and want to make change not for doma, but is VIS is present in system. As I understand we should check that  AOS_VIS_PLUGINS is not empty in local.conf.
```
recipes-core/netbase$ cat netbase_%.bbappend 
do_install_append () {
	if [${@bb.utils.contains('AOS_VIS_PLUGINS', '', false, true, d)}]; then
		# VIS server in DomD
		echo "192.168.0.1 wwwivi" >> ${D}${sysconfdir}/hosts
	fi
}
```
Not tested.

**Comment by rshym** [comment]
Also pay attention that signed off by ihor.usyk@google.com

**Comment by iusyk** [comment]
@rshym @andr2000 @otyshchenko1 I found : the variables AOS_VIS_PLUGINS and GUEST_INSTALL are not available in the recipe, at this moment I see 2 options
1. use the committed code
2. user the do_install without any preconditions 

your opinion is important

**Comment by andr2000** [comment]
Just make AOS_VIS_PLUGINS available

**Comment by andr2000** [comment]
https://github.com/xen-troops/meta-xt-prod-devel/blob/master/recipes-domd/domd-image-weston/domd-image-weston.bbappend#L159

**Comment by iusyk** [comment]
@otyshchenko1 @otyshchenko1 @rshym please take a look at final version
build results are
domd-image-weston/1.0-r0/repo/build/tmp/work/aarch64-poky-linux/netbase/1_5.4-r0/packages-split/netbase/etc/hosts:192.168.0.1 wwwivi
domd-image-weston/1.0-r0/repo/build/tmp/work/aarch64-poky-linux/netbase/1_5.4-r0/image/etc/hosts:192.168.0.1 wwwivi

**Comment by rshym** [comment]
As I understand from previous comment, AOS_VIS_PLUGINS is not available at netbase_%.bbappend.

**Comment by rshym** [comment]
As I understand from previous comment, AOS_VIS_PLUGINS is not available at netbase_%.bbappend. So, how do you get expected result in /etc/hosts ?

**Comment by rshym** [comment]
Thanks for offline clarification.
LGTM

**Comment by rshym** [comment]
Can we merge it?

**Comment by andr2000** [comment]
`Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>`

**Pull request merged**
