### PR TITLE
Update doma*.cfg

### PR DESCRIPTION
**Pull request by rshym**
These changes are propagation of part of https://github.com/xen-troops/meta-xt-prod-devel/pull/242 for domA related configs.

Not tested yet.

### CODE REVIEW

**Comment by rshym** [comment]
Two open questions I could be glad to hear during review:
1) May be it's better to squash commits to one "dom0: Propagate domu related changes to doma configs"
2) Maybe someone has idea of better name for doma-salvator-generic.cfg.

**Comment by rshym** [comment]
Tested by build for devel-doma-kf (domd and doma excluded from build, as far as change affects assembling of text configs inside dom0).
- assembly of doma.cfg - OK
- pvcamera distro_feature enabled/disabled - OK

Works as expected.

**Comment by otyshchenko1** [comment]
lgtm, btw s/doma-salvator-generic.cfg/doma-generic-h3.cfg ?

**Comment by rshym** [comment]
> lgtm, btw s/doma-salvator-generic.cfg/doma-generic-h3.cfg ?

Thanks for suggestion. Renamed.

**Pull request merged**
